### ISSUE TITLE
Calculations with easter date not working

### ISSUE THREAD

**Issue by MazeChaZer** [wtfuii/german-holiday#2]
Using the `+` operator on integer and date objects does not work.

Example for Karfreitag:

```
> holidayCheck.holidayCheck(new Date(2016, 2, 25), 'NW');
false
```

The correct way to add days to a date object is:

``` js
var easter = easterCalculation(2016);
var ostermontag = new Date(easter.valueOf()).setDate(easter.getDate() + 1);
```

The part `new Date(easter.valueOf())` creates a clone of the easter date object to keep it intact.

**Comment by wtfuii** [comment]
Huge bug, thank you!
